#!/bin/sh
set -eu

RUNTIME_ENV_FILE="${SDR_RUNTIME_ENV_FILE:-/run/sdr-env/.env}"

if [ ! -s "$RUNTIME_ENV_FILE" ]; then
  echo "FATAL: persistent SDR runtime env is missing at $RUNTIME_ENV_FILE" >&2
  exit 78
fi

# Values injected by the current deployment are authoritative. Preserve them
# before loading the persistent migration env, then restore non-empty values.
DEPLOY_SDR_BUILD_REF="${SDR_BUILD_REF:-}"
DEPLOY_CAREER_GENERATION="${CAREER_GENERATION:-}"
DEPLOY_DISABLE_AUTH="${DISABLE_AUTH:-}"
DEPLOY_DASHBOARD_ACCESS_MODE="${DASHBOARD_ACCESS_MODE:-}"
DEPLOY_DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-}"
DEPLOY_DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-}"
DEPLOY_SDR_ADMIN_PASSWORD="${SDR_ADMIN_PASSWORD:-}"
DEPLOY_OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-${GTM_RESEARCH_OPENROUTER_API_KEY:-}}"
DEPLOY_OPENROUTER_FAST_MODEL="${OPENROUTER_FAST_MODEL:-}"
DEPLOY_OPENROUTER_DEEP_MODEL="${OPENROUTER_DEEP_MODEL:-}"
DEPLOY_SIGNALHIRE_API_KEY="${SIGNALHIRE_API_KEY:-}"
DEPLOY_MILLIONVERIFIER_API_KEY="${MILLIONVERIFIER_API_KEY:-}"
DEPLOY_TAVILY_API_KEY="${TAVILY_API_KEY:-}"
DEPLOY_APOLLO_API_KEY="${APOLLO_API_KEY:-}"
DEPLOY_GEMINI_API_KEY="${GEMINI_API_KEY:-}"
DEPLOY_ACQUISITION_OWNER_TOKEN="${ACQUISITION_OWNER_TOKEN:-}"
DEPLOY_ACQUISITION_OWNER_IDS="${ACQUISITION_OWNER_IDS:-}"
DEPLOY_HUBSPOT_PRIVATE_APP_TOKEN="${HUBSPOT_PRIVATE_APP_TOKEN:-}"
DEPLOY_GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
DEPLOY_GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
DEPLOY_GOOGLE_REDIRECT_URI="${GOOGLE_REDIRECT_URI:-}"
DEPLOY_GOOGLE_TOKEN_ENCRYPTION_KEY="${GOOGLE_TOKEN_ENCRYPTION_KEY:-}"
DEPLOY_MAQSAM_INGEST_SECRET="${MAQSAM_INGEST_SECRET:-}"
DEPLOY_MAQSAM_BASIC_AUTH="${MAQSAM_BASIC_AUTH:-}"
DEPLOY_MAQSAM_ACCESS_KEY="${MAQSAM_ACCESS_KEY:-}"
DEPLOY_MAQSAM_ACCESS_SECRET="${MAQSAM_ACCESS_SECRET:-}"
DEPLOY_MAQSAM_TARGET_AGENT_EMAIL="${MAQSAM_TARGET_AGENT_EMAIL:-}"
DEPLOY_MAQSAM_SYNC_INTERVAL_SECONDS="${MAQSAM_SYNC_INTERVAL_SECONDS:-}"
DEPLOY_MAQSAM_SYNC_LOOKBACK_SECONDS="${MAQSAM_SYNC_LOOKBACK_SECONDS:-}"
DEPLOY_MAQSAM_SYNC_PAGE_COUNT="${MAQSAM_SYNC_PAGE_COUNT:-}"

set -a
# shellcheck disable=SC1090
. "$RUNTIME_ENV_FILE"
set +a

# Cancelled vendors must never survive via an old persistent .env. Do not log
# values; only remove matching variable names from this process environment.
for RETIRED_KEY in $(env | cut -d= -f1 | grep -E '^(SMARTLEAD_|PRIMEFORGE_|PRIME_FORGE_|CLEARBIT_|NEVERBOUNCE_)' || true); do
  unset "$RETIRED_KEY"
done

restore_if_set() {
  key="$1"
  value="$2"
  # Empty deploy-time values are intentionally optional. Under `set -e`, the
  # old `[ -n "$value" ] && export ...` form returned status 1 for an empty
  # value and killed PID 1 before the app could emit any logs.
  if [ -n "$value" ]; then
    export "$key=$value"
  fi
  return 0
}

restore_if_set SDR_BUILD_REF "$DEPLOY_SDR_BUILD_REF"
restore_if_set CAREER_GENERATION "$DEPLOY_CAREER_GENERATION"
restore_if_set DISABLE_AUTH "$DEPLOY_DISABLE_AUTH"
restore_if_set DASHBOARD_ACCESS_MODE "$DEPLOY_DASHBOARD_ACCESS_MODE"
restore_if_set DASHBOARD_USERNAME "$DEPLOY_DASHBOARD_USERNAME"
restore_if_set DASHBOARD_PASSWORD "$DEPLOY_DASHBOARD_PASSWORD"
restore_if_set SDR_ADMIN_PASSWORD "$DEPLOY_SDR_ADMIN_PASSWORD"
restore_if_set SIGNALHIRE_API_KEY "$DEPLOY_SIGNALHIRE_API_KEY"
restore_if_set MILLIONVERIFIER_API_KEY "$DEPLOY_MILLIONVERIFIER_API_KEY"
restore_if_set TAVILY_API_KEY "$DEPLOY_TAVILY_API_KEY"
restore_if_set APOLLO_API_KEY "$DEPLOY_APOLLO_API_KEY"
restore_if_set GEMINI_API_KEY "$DEPLOY_GEMINI_API_KEY"
restore_if_set ACQUISITION_OWNER_TOKEN "$DEPLOY_ACQUISITION_OWNER_TOKEN"
restore_if_set ACQUISITION_OWNER_IDS "$DEPLOY_ACQUISITION_OWNER_IDS"
restore_if_set HUBSPOT_PRIVATE_APP_TOKEN "$DEPLOY_HUBSPOT_PRIVATE_APP_TOKEN"
restore_if_set GOOGLE_CLIENT_ID "$DEPLOY_GOOGLE_CLIENT_ID"
restore_if_set GOOGLE_CLIENT_SECRET "$DEPLOY_GOOGLE_CLIENT_SECRET"
restore_if_set GOOGLE_REDIRECT_URI "$DEPLOY_GOOGLE_REDIRECT_URI"
restore_if_set GOOGLE_TOKEN_ENCRYPTION_KEY "$DEPLOY_GOOGLE_TOKEN_ENCRYPTION_KEY"
restore_if_set MAQSAM_INGEST_SECRET "$DEPLOY_MAQSAM_INGEST_SECRET"
restore_if_set MAQSAM_BASIC_AUTH "$DEPLOY_MAQSAM_BASIC_AUTH"
restore_if_set MAQSAM_ACCESS_KEY "$DEPLOY_MAQSAM_ACCESS_KEY"
restore_if_set MAQSAM_ACCESS_SECRET "$DEPLOY_MAQSAM_ACCESS_SECRET"
restore_if_set MAQSAM_TARGET_AGENT_EMAIL "$DEPLOY_MAQSAM_TARGET_AGENT_EMAIL"
restore_if_set MAQSAM_SYNC_INTERVAL_SECONDS "$DEPLOY_MAQSAM_SYNC_INTERVAL_SECONDS"
restore_if_set MAQSAM_SYNC_LOOKBACK_SECONDS "$DEPLOY_MAQSAM_SYNC_LOOKBACK_SECONDS"
restore_if_set MAQSAM_SYNC_PAGE_COUNT "$DEPLOY_MAQSAM_SYNC_PAGE_COUNT"

export SDR_BUILD_REF="${SDR_BUILD_REF:-unknown}"
export CAREER_GENERATION="${CAREER_GENERATION:-v3}"
export DISABLE_AUTH="${DISABLE_AUTH:-false}"
export DASHBOARD_ACCESS_MODE="${DASHBOARD_ACCESS_MODE:-public}"
export DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-talentera}"
export DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-}"
export SDR_ADMIN_PASSWORD="${SDR_ADMIN_PASSWORD:-}"
export SIGNALHIRE_API_KEY="${SIGNALHIRE_API_KEY:-}"
export MILLIONVERIFIER_API_KEY="${MILLIONVERIFIER_API_KEY:-}"
export TAVILY_API_KEY="${TAVILY_API_KEY:-}"
export APOLLO_API_KEY="${APOLLO_API_KEY:-}"
export GEMINI_API_KEY="${GEMINI_API_KEY:-}"
export ACQUISITION_OWNER_TOKEN="${ACQUISITION_OWNER_TOKEN:-}"
export ACQUISITION_OWNER_IDS="${ACQUISITION_OWNER_IDS:-}"
export HUBSPOT_PRIVATE_APP_TOKEN="${HUBSPOT_PRIVATE_APP_TOKEN:-}"
export GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
export GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
export GOOGLE_REDIRECT_URI="${GOOGLE_REDIRECT_URI:-https://sdr.dashboardtalentera.tech/api/google/callback}"
export GOOGLE_TOKEN_ENCRYPTION_KEY="${GOOGLE_TOKEN_ENCRYPTION_KEY:-}"
export MAQSAM_INGEST_SECRET="${MAQSAM_INGEST_SECRET:-}"
export MAQSAM_BASIC_AUTH="${MAQSAM_BASIC_AUTH:-}"
export MAQSAM_ACCESS_KEY="${MAQSAM_ACCESS_KEY:-}"
export MAQSAM_ACCESS_SECRET="${MAQSAM_ACCESS_SECRET:-}"
export MAQSAM_TARGET_AGENT_EMAIL="${MAQSAM_TARGET_AGENT_EMAIL:-m.chedid@bayt.net}"
export MAQSAM_SYNC_INTERVAL_SECONDS="${MAQSAM_SYNC_INTERVAL_SECONDS:-600}"
export MAQSAM_SYNC_LOOKBACK_SECONDS="${MAQSAM_SYNC_LOOKBACK_SECONDS:-10800}"
export MAQSAM_SYNC_PAGE_COUNT="${MAQSAM_SYNC_PAGE_COUNT:-12}"

if [ -n "$DEPLOY_OPENROUTER_API_KEY" ]; then
  OPENROUTER_API_KEY="$DEPLOY_OPENROUTER_API_KEY"
elif [ -z "${OPENROUTER_API_KEY:-}" ] && [ -n "${GTM_RESEARCH_OPENROUTER_API_KEY:-}" ]; then
  OPENROUTER_API_KEY="$GTM_RESEARCH_OPENROUTER_API_KEY"
fi
export OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"

if [ -n "$DEPLOY_OPENROUTER_FAST_MODEL" ]; then OPENROUTER_FAST_MODEL="$DEPLOY_OPENROUTER_FAST_MODEL"; fi
if [ -n "$DEPLOY_OPENROUTER_DEEP_MODEL" ]; then OPENROUTER_DEEP_MODEL="$DEPLOY_OPENROUTER_DEEP_MODEL"; fi
OPENROUTER_FAST_MODEL="${OPENROUTER_FAST_MODEL:-openai/gpt-4.1-nano}"
OPENROUTER_DEEP_MODEL="${OPENROUTER_DEEP_MODEL:-openai/gpt-4.1-mini}"
export OPENROUTER_FAST_MODEL OPENROUTER_DEEP_MODEL

if [ -n "${OPENROUTER_API_KEY:-}" ]; then
  echo "OpenRouter gateway: configured; fast=${OPENROUTER_FAST_MODEL}; deep=${OPENROUTER_DEEP_MODEL}"
else
  echo "OpenRouter gateway: NOT configured; paid AI features are disabled"
fi

if [ -n "${SIGNALHIRE_API_KEY:-}" ]; then
  echo "Prospecting SignalHire: configured"
else
  echo "Prospecting SignalHire: NOT configured"
fi

echo "SDR runtime: build=${SDR_BUILD_REF}; careerGeneration=${CAREER_GENERATION}; accessMode=${DASHBOARD_ACCESS_MODE}; disableAuth=${DISABLE_AUTH}"

if [ "${SDR_WORKER:-}" = "maqsam-sync" ]; then
  echo "Starting Maqsam internal sync worker"
  exec node scripts/maqsam-sync.mjs
fi

exec node server.js
