#!/bin/sh
set -eu

RUNTIME_ENV_FILE="${SDR_RUNTIME_ENV_FILE:-/run/sdr-env/.env}"

if [ ! -s "$RUNTIME_ENV_FILE" ]; then
  echo "FATAL: persistent SDR runtime env is missing at $RUNTIME_ENV_FILE" >&2
  exit 78
fi

# Values injected by Docker Compose / GitHub Actions are authoritative for a
# deployment. Keep them before sourcing the persistent VPS env because a stale
# key in that file must never roll production back to an older build or secret.
DEPLOY_SDR_BUILD_REF="${SDR_BUILD_REF:-}"
DEPLOY_CAREER_GENERATION="${CAREER_GENERATION:-}"
DEPLOY_DISABLE_AUTH="${DISABLE_AUTH:-}"
DEPLOY_DASHBOARD_ACCESS_MODE="${DASHBOARD_ACCESS_MODE:-}"
DEPLOY_DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-}"
DEPLOY_DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-}"
DEPLOY_SDR_ADMIN_PASSWORD="${SDR_ADMIN_PASSWORD:-}"
DEPLOY_OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-${GTM_RESEARCH_OPENROUTER_API_KEY:-}}"
DEPLOY_OPENROUTER_FAST_MODEL="${OPENROUTER_FAST_MODEL:-}"
DEPLOY_OPENROUTER_DEEP_MODEL="${OPENROUTER_DEEP_MODEL:-}"
DEPLOY_SIGNALHIRE_API_KEY="${SIGNALHIRE_API_KEY:-}"
DEPLOY_TAVILY_API_KEY="${TAVILY_API_KEY:-}"
DEPLOY_APOLLO_API_KEY="${APOLLO_API_KEY:-}"
DEPLOY_ACQUISITION_OWNER_TOKEN="${ACQUISITION_OWNER_TOKEN:-}"
DEPLOY_ACQUISITION_OWNER_IDS="${ACQUISITION_OWNER_IDS:-}"

set -a
# shellcheck disable=SC1090
. "$RUNTIME_ENV_FILE"
set +a

# Restore non-empty deployment values after the persistent env has loaded.
# Runtime-only values that are not injected by deployment still come from the
# persistent env as before.
if [ -n "$DEPLOY_SDR_BUILD_REF" ]; then SDR_BUILD_REF="$DEPLOY_SDR_BUILD_REF"; fi
if [ -n "$DEPLOY_CAREER_GENERATION" ]; then CAREER_GENERATION="$DEPLOY_CAREER_GENERATION"; fi
if [ -n "$DEPLOY_DISABLE_AUTH" ]; then DISABLE_AUTH="$DEPLOY_DISABLE_AUTH"; fi
if [ -n "$DEPLOY_DASHBOARD_ACCESS_MODE" ]; then DASHBOARD_ACCESS_MODE="$DEPLOY_DASHBOARD_ACCESS_MODE"; fi
if [ -n "$DEPLOY_DASHBOARD_USERNAME" ]; then DASHBOARD_USERNAME="$DEPLOY_DASHBOARD_USERNAME"; fi
if [ -n "$DEPLOY_DASHBOARD_PASSWORD" ]; then DASHBOARD_PASSWORD="$DEPLOY_DASHBOARD_PASSWORD"; fi
if [ -n "$DEPLOY_SDR_ADMIN_PASSWORD" ]; then SDR_ADMIN_PASSWORD="$DEPLOY_SDR_ADMIN_PASSWORD"; fi
if [ -n "$DEPLOY_SIGNALHIRE_API_KEY" ]; then SIGNALHIRE_API_KEY="$DEPLOY_SIGNALHIRE_API_KEY"; fi
if [ -n "$DEPLOY_TAVILY_API_KEY" ]; then TAVILY_API_KEY="$DEPLOY_TAVILY_API_KEY"; fi
if [ -n "$DEPLOY_APOLLO_API_KEY" ]; then APOLLO_API_KEY="$DEPLOY_APOLLO_API_KEY"; fi
if [ -n "$DEPLOY_ACQUISITION_OWNER_TOKEN" ]; then ACQUISITION_OWNER_TOKEN="$DEPLOY_ACQUISITION_OWNER_TOKEN"; fi
if [ -n "$DEPLOY_ACQUISITION_OWNER_IDS" ]; then ACQUISITION_OWNER_IDS="$DEPLOY_ACQUISITION_OWNER_IDS"; fi

export SDR_BUILD_REF="${SDR_BUILD_REF:-unknown}"
export CAREER_GENERATION="${CAREER_GENERATION:-v3}"
export DISABLE_AUTH="${DISABLE_AUTH:-false}"
export DASHBOARD_ACCESS_MODE="${DASHBOARD_ACCESS_MODE:-public}"
export DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-talentera}"
export DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-}"
export SDR_ADMIN_PASSWORD="${SDR_ADMIN_PASSWORD:-}"
export SIGNALHIRE_API_KEY="${SIGNALHIRE_API_KEY:-}"
export TAVILY_API_KEY="${TAVILY_API_KEY:-}"
export APOLLO_API_KEY="${APOLLO_API_KEY:-}"
export ACQUISITION_OWNER_TOKEN="${ACQUISITION_OWNER_TOKEN:-}"
export ACQUISITION_OWNER_IDS="${ACQUISITION_OWNER_IDS:-}"

if [ -n "$DEPLOY_OPENROUTER_API_KEY" ]; then
  OPENROUTER_API_KEY="$DEPLOY_OPENROUTER_API_KEY"
elif [ -z "${OPENROUTER_API_KEY:-}" ] && [ -n "${GTM_RESEARCH_OPENROUTER_API_KEY:-}" ]; then
  # Backward-compatible migration from the retired GTM Research secret name.
  OPENROUTER_API_KEY="$GTM_RESEARCH_OPENROUTER_API_KEY"
fi
export OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"

# Keep the old name populated for any older local code during the transition.
if [ -n "${OPENROUTER_API_KEY:-}" ]; then
  GTM_RESEARCH_OPENROUTER_API_KEY="$OPENROUTER_API_KEY"
  export GTM_RESEARCH_OPENROUTER_API_KEY
fi

if [ -n "$DEPLOY_OPENROUTER_FAST_MODEL" ]; then OPENROUTER_FAST_MODEL="$DEPLOY_OPENROUTER_FAST_MODEL"; fi
if [ -n "$DEPLOY_OPENROUTER_DEEP_MODEL" ]; then OPENROUTER_DEEP_MODEL="$DEPLOY_OPENROUTER_DEEP_MODEL"; fi
OPENROUTER_FAST_MODEL="${OPENROUTER_FAST_MODEL:-openai/gpt-4.1-nano}"
OPENROUTER_DEEP_MODEL="${OPENROUTER_DEEP_MODEL:-openai/gpt-4.1-mini}"
export OPENROUTER_FAST_MODEL OPENROUTER_DEEP_MODEL

if [ -n "${OPENROUTER_API_KEY:-}" ]; then
  echo "OpenRouter gateway: configured; fast=${OPENROUTER_FAST_MODEL}; deep=${OPENROUTER_DEEP_MODEL}"
else
  echo "OpenRouter gateway: NOT configured; paid AI features are disabled"
fi

if [ -n "${SIGNALHIRE_API_KEY:-}" ]; then
  echo "Prospecting SignalHire: configured"
else
  echo "Prospecting SignalHire: NOT configured"
fi

echo "SDR runtime: build=${SDR_BUILD_REF}; careerGeneration=${CAREER_GENERATION}; accessMode=${DASHBOARD_ACCESS_MODE}; disableAuth=${DISABLE_AUTH}"

exec node server.js
